修复valine不可用
KeJunMao/jekyll-theme-mdui pull request #57
Opened 2021-02-07 11:44 UTC by w311ang

根据https://valine.js.org/configuration.html，剔除失效变量，修改更名变量

2021-02-08 06:29 UTC, KeJunMao requested changes
谢谢，是否能将[默认配置项](https://github.com/KeJunMao/jekyll-theme-mdui/blob/master/_data/site.yml)，以及对应[文档](http://mdui.kejun.me/#/zh-cn/comment?id=valine)一并改了

2021-02-08 09:34 UTC, w311ang commented
> 谢谢，是否能将[默认配置项](https://github.com/KeJunMao/jekyll-theme-mdui/blob/master/_data/site.yml)，以及对应[文档](http://mdui.kejun.me/#/zh-cn/comment?id=valine)一并改了

2021-02-08 09:37 UTC, w311ang commented
> 谢谢，是否能将[默认配置项](https://github.com/KeJunMao/jekyll-theme-mdui/blob/master/_data/site.yml)，以及对应[文档](http://mdui.kejun.me/#/zh-cn/comment?id=valine)一并改了

文档好像没什么可改的吧

2021-02-08 09:38 UTC, w311ang commented
> 谢谢，是否能将[默认配置项](https://github.com/KeJunMao/jekyll-theme-mdui/blob/master/_data/site.yml)，以及对应[文档](http://mdui.kejun.me/#/zh-cn/comment?id=valine)一并改了

#59 对于默认配置的修改

2021-02-10 13:50 UTC, merged

2021-02-10 13:50 UTC, KeJunMao commented
太谢谢啦！